name: Build Pipeline

on: [push, pull_request, workflow_dispatch]

jobs:
  Palladio-Bench-Product:
    uses: PalladioSimulator/Palladio-Build-ActionsPipeline/.github/workflows/build.yml@master
    with:
      use-display-output: true
      no-caching: true
      runner-label: ubuntu-latest
      deploy-updatesite: 'products/org.palladiosimulator.product/target/deploy'
    secrets:
      SERVER_SSH_KEY: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
      REMOTE_HOST: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
      REMOTE_PORT: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
      REMOTE_USER: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
      REMOTE_TARGET: ${{ secrets.DEPLOYMENT_REMOTE_TARGET }}
